---
output:
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::word_document2: default
  bookdown::html_document2: default
documentclass: book
bibliography: references.bib
---

\part{A continental perspective}

```{block type='savequote', include=knitr::is_latex_output()}
Delmore, K.,* **Van Doren, B.M.**,* Conway, G.J., Curk, T., Garrido-Garduño, T., Germain, R.R., Hasselmann, T., Hiemer, D., van der Jeugd, H.P., Justen, H., Lugo Ramos, J.S., Maggini, I., Phillips, R.J., Remisiewicz, M., Roberts, G.C.M., Sheldon, B.C., Vogl, W., and Liedvogel, M. Formatted for *Current Biology*.
\begin{scriptsize} * Equal contributions. \end{scriptsize}
```

<!-- 
Notes for adding an opening quote in PDF output:
i) add the reference for the quote with the chunk option quote_author="my author name",
ii) include=knitr::opts_knit$get('rmarkdown.pandoc.to') == 'latex' means that these quotes are only included when output is latex (in HTML output, it would appear by the end of the previous page)
iii) You can't use markdown syntax inside chunk options, so if you want to e.g. italicise a book name in the quote reference use a 'text reference': Create a named piece of text with '(ref:label-name) My text', then link to this in the chunk option with quote_author='(ref:label-name)'
-->

<!-- # Versatile migratory strategies and evolutionary insights revealed by tracks of wild Eurasian blackcaps {#blackcap-geo} -->
# Versatile migratory strategies in blackcaps {#blackcap-geo}
<!-- \chapter[Migratory strategies in blackcaps across Europe]{Migratory strategies in blackcaps across Europee} -->
<!-- \chaptermark{Migratory strategies in blackcaps across Europe} -->

<!-- \begin{flushright} -->
<!-- \textbf{Submitted to \textit{Current Biology}} -->
<!-- \end{flushright} -->


<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of this chapter. Reference labels will automatically be generated if you don't specify them, as the lowercase title with spaces replaced by hypens (e.g. r-markdown-basics). Look for the reference to this label at the beginning of the next chapter.
-->

```{r, include=F}
knitr::opts_knit$set(root.dir = "/Users/Benjamin/Documents/Oxford/Blackcaps/Blackcap_Geolocator_Analysis/blackcap_geo_comparative")
```

```{r include=TRUE,echo=FALSE}
print_references <- FALSE
```

```{r blackcap-geo, child = '/Users/Benjamin/Documents/Oxford/Blackcaps/Blackcap_Geolocator_Analysis/blackcap_geo_comparative/scripts/Blackcap_geolocator_paper.Rmd',eval=TRUE}
```


```{r, include=F}
knitr::opts_knit$set(root.dir = "/Users/Benjamin/Documents/Oxford/Thesis/oxforddown")
```

