---
output:
  bookdown::word_document2: default
  bookdown::pdf_document2:
    template: templates/brief_template.tex
  bookdown::html_document2: default
documentclass: book
bibliography: references.bib
csl: /Users/Benjamin/Zotero/styles/ecology.csl
---

# General Discussion {-}
\markboth{General Discussion}{General Discussion}


<!-- + Summary of results? -->
<!-- Because each chapter contains its own detailed discussion, I focus here on themes that bridge multiple chapters.  -->


<!-- ## Determinants of flexibility in the face of change {-} -->
## The power of perspectives across scales {-}

<!-- Migratory birds form a network of organisms that connect the globe. Today, climate and land cover changes are transforming the world's ecosystems at an increasingly alarming rate. Organisms are responding, but they may not be adapting fast enough [@devictorBirdsAreTracking2008; @devictorDifferencesClimaticDebts2012; @mayorIncreasingPhenologicalAsynchrony2017]. -->

Understanding natural phenomena as complex as bird migration requires a multilevel approach, as individual-level programs and reaction norms interact with population processes and broad biotic and abiotic factors. In this thesis, I have explored several perspectives on change and flexibility in avian migration, focusing on the contributions of the innate migratory program, birds' responses to environmental cues and conditions, and the influence of human activity on migratory behavior. In **chapter \@ref(stonechats)**, I demonstrated that stonechats (genus *Saxicola*) possess inherited migratory programs that vary predictably among taxa according to their migratory behavior. However, these programs are not the sole determinant of migratory phenotype, especially among partial migrants, implying that environmental factors can readily interact with the inherited program. In **chapter \@ref(flycatchers)**, I combined field and laboratory studies to present evidence of changes in the innate migratory program of a long-distance migrant, the pied flycatcher (*Ficedula hypoleuca*), showing that ongoing responses of migratory birds to climate change can involve not only phenotypic plasticity, but microevolutionary change as well. In **chapter \@ref(blackcap-geo)**, I examined variation in the migratory behavior of the Eurasian blackcap (*Sylvia atricapilla*) across its European range, illustrating two different ways that natural selection can act on songbird migration: (1) to maintain opposing migratory strategies over short distances, in the case of a migratory divide,  and (2) to enable the spread of a novel strategy across a wide range, in the case of individuals wintering in the British Isles. In **chapter \@ref(forecast)**, I showed that migratory flexibility is important not only on evolutionary timescales, but also to enable short-term responses to variable environmental conditions during active migratory flights. These responses are predictable enough to reliably forecast avian movements across continental extents. In **chapter \@ref(lights)**, I examined how artificial light at night can drastically affect migratory journeys, an important example of anthropogenic impacts on bird migration. Finally, in **chapter \@ref(blackcap-uk)**, I returned to the blackcap to show how human activity can impact not only migrants' in-flight behaviors, but also shape their broader ecology. Overall, this body of work shows that migratory birds' flexibility stems from a range of sources, innate and external, and that the presence of variation in migratory phenotype may be key to enabling responses to environmental change.



<!-- **chapter \@ref(stonechats)** -->
<!-- **chapter \@ref(flycatchers)** -->
<!-- **chapter \@ref(blackcap-geo)** -->
<!-- **chapter \@ref(forecast)** -->
<!-- **chapter \@ref(lights)** -->
<!-- **chapter \@ref(blackcap-uk)** -->


<!-- Are species adjusting fast enough to match the pace of environmental change?  -->

<!--   + Adapting to a changing world -->
<!--   + Are species adjusting fast enough?  -->
<!--   + Passerine migrants have hard coded programs (ch 1). In some species their rigidity may hinder rapid responses to change. Yet I find evidence that evolutionary change may be occurring even in a species with well documented rigidity (ch 2). However, it is unclear whether change is occurring fast enough. Indeed, I examine blackcaps, a species that is thriving despite change, and I find strong evidence for flexibility in their movements and ecology (ch 3 and 6). This flexibility appears to be driven by the large variation present in this species. Lesson: variation is key to adaptation. Darwin.  -->
  
## The interplay of variation and flexibility {-}

Variation is the engine of evolutionary change, providing populations with the raw material on which natural selection can act. Taxa with greater natural variation will be the most flexible---and best able to adapt to changing conditions.
Among migratory birds, variation and flexibility are linked: long-distance migrants with rigid timing programs show the most consistency in phenotype [@gwinnerCircadianCircannualProgrammes1996; @gwinnerCircadianCircannualProgrammes1996]. Shorter distance migrants show greater variation in behavior and less rigidly programmed migrations [@bertholdCircannualePeriodikBei1972a; @gwinnerCircannualRhythmsTropical1991]. These insights lead to the expectation that short-distance migrants will more quickly respond to climate change, a hypothesis supported by current evidence [@butlerDisproportionateEffectGlobal2003; @usuiTemporalShiftsTemperature2017]. 

In this thesis, the contrast between short- and long-distance migrants is evident in **chapter \@ref(stonechats)**, where stonechat taxa with longer migrations showed less variation in behavior. Siberian stonechats nearly always showed migratory restlessness, whereas individuals from Irish and Kenyan populations frequently did not. Siberian stonechats are obligate long-distance migrants, Irish stonechats are partial migrants, and Kenyan stonechats are residents.

In **chapter \@ref(flycatchers)**, I observed a stark contrast between the phenotypic variation observed in the 2002 cohort of pied flycatchers and the older 1981 cohort, despite both groups having been raised under identical conditions. Although the experimental sample sizes were small, individual variation in winter and spring timing traits was greater in the 2002 cohort among both males and females. This pattern could suggest that climate change---itself variable and volatile---may be selecting for increased variation in phenotypes. 

Blackcaps show broad variation in migratory traits at both individual and population levels. Populations of blackcaps range from entirely sedentary to fully migratory [@crampSylviaAtricapillaBlackcap1992], and the results from **chapters \@ref(blackcap-geo) and \@ref(blackcap-uk)** highlight the variability in blackcaps' individual strategies. Blackcaps breeding near the central European migratory divide showed a large spread in migratory direction as well as in timing. In British gardens, blackcaps also showed large individual variation in behavior, with some individuals reliably using garden feeding stations in a range of weather conditions and others doing so primarily during harsher weather. Blackcaps also have substantial diet flexibility, which may contribute to their ability to use gardens [@hardyWinterFoodsBlackcaps1978; @reyDietPlasticityBlackcap1999].



<!-- focused on only one population of pied flycatchers, work across populations has showed (??) link between adjustment and decline doesn't necessarily get at question of variation -->

<!--  This pattern is borne out in bird migration, where the the least variable   -->

<!--   + Variation is the engine of evolutionary change - it's what makes populations able to evolve -->
<!--   + In terms of the flexibility of migratory behavior, we see that the least flexible species are also generally the least variable ones -->
<!--     + Those that have rigidly timed migration programs -- which are also likely to be the long-distance migrants -->
<!--     + This leads to the inference that short distance migrants are more flexible and will have an easier time responding to climate change (refs) -->
<!--   + In my research, stonechat taxa that were long distance migrants showed the greatest consistency in migratory behavior, nearly always showing strong migratory restlessness, whereas individuals from partially migratory and resident populations did not always show migratory restlessness. This might imply greater plasticity in the migratory program of the latter populations / greater sensitivity to environmental factors  -->
<!--   + Although my work on pied flycatchers focused on only one population, work across populations has showed (??) link between adjustment and decline doesn't necessarily get at question of variation -->
<!--     + However we did see a tendency for the recent cohort of captive flycatchers to show much greater variation in phenotypes under identical conditions, albeit with a small sample sie. This could suggest that climate change, which itself is volatile and variable, is selecting for increased variation in phenotypes, which in turn may lead to increased flexibility in the future. But speculative  -->

<!--   + In blackcaps, broad variation present in migratory traits both at the species level (across populations that vary greatly in their extent of migratory behavior), and at finer scales -- individual spread of directions in divide, dietary flexibility [cite] which has allowed them to take advantage of supplemental feeding, whereas other warblers (chiffchaffs?), even though they have responded to climate change, have done so in a much more limited way. Also individual differences in strategies in the UK wintering population, where some are more tied to gardens than others. In this case, both in various aspects of their biology, the flexibility of blackcaps may stem from variation, just as this increased flexibilty empowers a population to be more variable overall -->





  <!-- + Is it all bad? -->
  <!--   + Blackcaps in the UK -- clear that human activity is influencing ecology and behavior of blackcaps (ch 3, ch 6). Is this bad? One could argue that they are filling a new niche. Humans are transforming the globe, and species that can take advantage of new opportunities will be the ones that survive.  (Is it bad to feed them? I don't think so.) -->
  <!--   + These highly flexible species are the first ones showing strong responses to climate change, but they likely preview the coming situation for other species that are slower to adjust (?) -->
  <!--   + So not all bad - for species that are flexible. For species that are less flexible, however, this is likely to be a major problem, and good evidence that a lack of flexibility is a major predictor of declines (cite pied fly, etc.). I provide evidence that pied flys and potentially other rigidly timed species can show evolutionary responses to changing phenology across multidecadal timescales (ch 2), but the overwhelming(?) evidence of declined linked to a lack of flexibility suggests that climate change may be outstripping the adjustment capacity of many species. [Potentially also cite Gulf work that shows no overall change in timing, potentially because of rigid timing programs?] -->
  
## Taking insights from the lab to the field---and back {-}  
  
Laboratory studies of migratory behavior have led to foundational insights into bird migration, including how migratory birds use the sun, stars, magnetic field, and polarized light to orient [@emlenMigratoryOrientationIndigo1967; @wiltschkoEvidenceInnateMagnetic1974; @alerstamRoleGeomagneticField1983; @akessonHowMigrantsGet2007]. Laboratory studies have also shown that songbirds' migratory behavior is innate and inherited [@bertholdGeneticControlMigratory1991; @helbigInheritanceMigratoryDirection1991] and even how birds respond to wind drift [@ableOrientationPasserineNocturnal1977; @mooreEvidenceRedeterminationMigratory1990]. At the same time, laboratory studies of migration can be limiting simply because they examine the behavior of caged birds, not free-flying individuals. Exactly how closely lab-derived assays correlate with wild phenotypes is still an open question, but recent research has shown that the migratory restlessness behavior of birds held in captivity may not always be directly comparable to migration in the wild. For example, resident populations may show migratory restlessness [@helmMigratoryRestlessnessEquatorial2006], and migrants that show restlessness every night in captivity may only undertake infrequent flights in the wild [@zunigaAbruptSwitchMigratory2016; @backmanActivityMigratoryFlights2017]. 

This thesis affirms the value of laboratory experiments for studying migration while also illustrating why scientists should be cautious in the extent of inference drawn from lab-derived proxies of wild behavior. In **chapter \@ref(flycatchers)**, I showed that the spring timing advances of captive-raised pied flycatchers taken from the wild were of a similar magnitude to those observed in a nearby wild population. In this case, the wild and laboratory-derived data were highly complementary: by excluding plasticity as a source of timing differences, the captive study provided key insight into change in the wild population, while at the same time affirming the relevance of laboratory data for understanding wild processes. Similarly, blackcap migration has been extensively studied in a laboratory setting, and **chapter \@ref(blackcap-geo)** provides an opportunity to compare previous lab-derived insights to new migration tracks of wild birds. Captive experiments that interbred blackcaps from populations with southwest and southeast migratory directions found that their offspring showed a spread of intermediate migratory directions [@helbigInheritanceMigratoryDirection1991]. The distribution of directions of wild birds tracked from the contact zone (**Chapter \@ref(blackcap-geo)**) was highly similar to the distribution of directions from the experiment. However, it is important to note that these tracks were from adult blackcaps originating in the migratory divide, while Helbig measured the offspring of parental populations captured away from the contact zone. In another instance, orientation experiments with British winterers found a broadly west-northwesterly autumn orientation, in contrast to the southwesterly orientation of German blackcaps [@bertholdRapidMicroevolutionMigratory1992]. Geolocator results showed that British winterers indeed migrate west and northwest to Britain from continental breeding areas (**Chapter \@ref(blackcap-geo)**). Finally, a captive timing experiment found that blackcaps exposed to British photoperiods initiated migration on average five days earlier than those exposed to Mediterranean photoperiods, estimating that birds wintering in these two areas would arrive on the breeding grounds 16 days apart due to the shorter migration durations of British winterers [@terrillEcophysiologicalAspectsRapid1990]. Results from wild-tracked blackcaps were broadly consistent with this result, yielding estimates of a six-day difference in departure and ten-day difference in arrival. Taken together, these results generally affirm the utility of laboratory experiments in the study of avian migratory behavior. 

Despite clear consistencies between laboratory results and the behavior of wild-tracked migrants, this thesis also highlights the caution needed when drawing inferences from laboratory proxies of migration. In **chapter \@ref(stonechats)**, I showed that the migratory phenotypes of wild populations do not necessarily align with activity measures derived from migratory restlessness data. In that chapter, Irish stonechats, which are partial migrants, showed intensities of spring migratory restlessness that were indistinguishable from those of Siberian stonechats, which are obligate long-distance migrants. In addition, I detected migratory restlessness in resident Kenyan stonechats and striking changes in restlessness with age, which might be related to plasticity or poorly understood learning processes. I also found that individuals with higher nocturnal migratory restlessness tended to be more active birds overall (measured from diurnal data), which necessitates further work on how restlessness relates to other traits and caution on its exclusive interpretation as a measure of migratory tendency [e.g. @bertholdEvolutionaryAspectsMigratory1988]. In blackcaps, although tracking results in **chapter \@ref(blackcap-geo)** were consistent with many insights derived from experiments in captivity (see previous paragraph), these experiments provided an incomplete picture. Orientation studies could not have determined that many blackcaps migrating south from the migratory divide would winter north of the Sahara. The experiments had concluded that a southerly migration direction would likely result in low survival [@helbigInheritanceMigratoryDirection1991], when in reality this direction is used by a large fraction of birds in the divide (**chapter \@ref(blackcap-geo)**). As a last example, Terrill and Berthold [-@terrillEcophysiologicalAspectsRapid1990] used an average migration rate of 45 km per day to estimate that British winterers would take 24 days to travel from Britain to Germany on spring migration. However, data from **chapter \@ref(blackcap-geo)** indicated that the spring migrations of British winterers were often only a few days long. Overall, care is necessary when interpreting results from laboratory proxies of migratory behavior.  


## Impacts of human activities on bird migration {-}

This thesis examines two examples of anthropogenic impacts on bird migration systems. The first is the behavioral alterations caused by the proliferation of artificial light at night. It is not known why migratory birds are attracted or disorientated by light pollution, but its negative influence on birds has been known for some time [@allenDestructionBirdsLighthouses1880]. Impacts of light pollution on birds can be severe and acute, as in cases of mass attraction and potentially mass mortality [e.g. **Chapter \@ref(lights)**; @richEcologicalConsequencesArtificial2013]. However, this is not the only way light pollution can impact avian migrants. Recent research suggests that light at night may influence the behavior of migrating birds across a landscape scale, drawing them towards urbanized areas where suitable terrestrial habitats can be scarce [@mclarenArtificialLightNight2018]. Fortunately, action to reduce light pollution can have immediate positive impacts and allow migrants to continue their flights unhindered (**Chapter \@ref(lights)**). 

Human activity has transformed much of the world and profoundly influenced the course of evolution of wild organisms [@palumbiHumansWorldGreatest2001; @boivinEcologicalConsequencesHuman2016; @sullivanHumanBehaviourLongterm2017]. Urbanization in particular has driven major phenotypic changes [@albertiGlobalUrbanSignatures2017] as organisms adapt to a human-dominated environment. As these changes reflect, one consequence of human activity is the creation of new and modified opportunities that wildlife can exploit. An obvious example of this phenomenon is the proliferation of supplemental feeding, which can have a range of impacts on the populations and behavior of wildlife [@galbraithSupplementaryFeedingRestructures2015; @coxHumanNatureInteractions2018; @plummerCompositionBritishBird2019]. This is especially true for birds, which are frequent beneficiaries of food provisioning. At least 45% percent of households feed birds in a number of countries, with higher provisioning rates in the United Kingdom [@galbraithRisksDriversWild2014; @daviesHouseholdFactorsInfluencing2012; @orrosWildBirdFeeding2015]. In the UK, this behavior is an important determinant of wintering blackcap presence and a driver of their behavior [**Chapter \@ref(blackcap-uk)**; @plummerSupplementaryFeedingGardens2015; @plummerCompositionBritishBird2019]. Garden bird feeding has likely facilitated the growth of the winter blackcap population by increasing winter survival, especially when harsh conditions increase energy demands [**Chapter \@ref(blackcap-uk)**; @plummerSupplementaryFeedingGardens2015]. This example demonstrates how a bird species with sufficient flexibility in migratory behavior can take advantage of novel resources. Blackcaps are not the only species adjusting migration in response to human-mediated changes in resource availability; species as diverse as white storks (*Ciconia ciconia*) and hummingbirds (Trochilidae) have adopted modified, shorter migrations [@satterfieldResponsesMigratorySpecies2018]. These highly flexible species are notable because of the speed of their response, and these examples may foreshadow similar ecological shifts in the future.

## Future directions and applications {-}

Natural systems are complex, reflecting the interplay among individual traits and behavior, external cues and stimuli, evolutionary processes, and other contributing factors. In this thesis, I have surveyed the drivers of bird migration across scales, seeking insights from individuals, species, and systems. 

### Dynamic approaches to conservation {-}

This work has direct implications for conservation initiatives striving to mitigate the impacts of human society on migrating birds. **Chapter \@ref(lights)** highlights the effects that artificial light can have on migrating birds, but it also shows that timely removal of light pollution can eliminate these acute impacts. Mitigation should focus on urban areas, which generate a disproportionate amount of light pollution---especially those along key migratory corridors (**Appendix \@ref(app-city-lights)**). Through migration forecasts (**Chapter \@ref(forecast)**), alerts could be established that warn of upcoming large migration events in time for people to turn off non-essential lighting. 

<!-- Through the use of migration forecasts (**chapter \@ref(forecast)**), programs could advise building and infrastructure managers and the public about when to turn off lights to protect birds. These advisories could be targeted to specific urban areas with the greatest impact (**Appendix \@ref(app-city-lights)**).  -->

### The genetic basis of migration {-}

For decades, we have known that key aspects of songbird migration are innately programmed and have a genetic basis [e.g. @bertholdGeneticBasisMigratory1981; @bertholdHeritabilityMigratoryActivity1994; @gwinnerCircannualClocksAvian1996; @helbigGeneticBasisMode1996; @pulidoFrequencyMigrantsMigratory1996]. Yet even today, we lack a meaningful understanding of the genetic architecture underlying migratory behavior. A large part of current knowledge stems from candidate genes associated with migration [e.g. @muellerIdentificationGeneAssociated2011; @sainoPolymorphismClockGene2015; @johnstonSeasonalGeneExpression2016; @lugoramosCandidateGenesMigration2017]. However, detected effects of candidate genes are generally limited and taxon- or sex-specific [@muellerIdentificationGeneAssociated2011; @sainoPolymorphismClockGene2015; @mettlerInteractionsCandidateGene2015; @bazziCandidateGenesHave2017; @bazziAdcyap1PolymorphismCovaries2016; @parody-merinoNoEvidenceAssociation2019; @ralstonLengthPolymorphismsTwo2019], with little evidence for general patterns [@lugoramosCandidateGenesMigration2017; but see e.g. @bazziClockGenePolymorphism2016]. Recent genomic work affirms a genetic basis of avian migratory behavior [@delmoreGeneticsSeasonalMigration2016; @toewsSelectionVPS13ALinked2019a], but we still lack any mechanistic or unified understanding of the processes involved. Epigenetic modifications could be important [@sainoMigrationPhenologyBreeding2017]. Fortunately, future work with blackcaps is promising: backcap migration clearly has a genetic basis [@bertholdRapidMicroevolutionMigratory1992; @helbigGeneticBasisMode1996] and the species shows minimal genetic structure across its migratory populations (Delmore et al., manuscript in review). This scenario is encouraging for identifying genetic variants that influence migratory phenotypes. Furthermore, in **chapter \@ref(blackcap-geo)**, I illustrate that the species shows widely varying migratory strategies, as well as a narrow cline in migratory direction across the central European migratory divide. The narrow cline suggests strong selection on migratory direction (or a related trait), which may be detectable via whole genome sequencing and analysis. 

### "Big Data" Ecology {-}

Ecology has entered an era of "big data," and **chapter \@ref(forecast)** provides one example of the many possible uses of large datasets in understanding the natural world. Integrating multiple datasets and modeling natural processes will lead to an even greater understanding of the intricacies of complex natural systems. For scientists studying migratory birds, large Doppler radar networks are but one source of big data. Citizen science initiatives now collect millions of observations from volunteer observers, and these data repositories are invaluable resources for understanding species behavior, distributions, and responses to change [e.g. @sullivanEBirdEnterpriseIntegrated2014]. Already, combining radar data and citizen science observations has led to new insights into bird migration (**Appendix \@ref(app-gulf)**). As repositories of many types of data grow, it will become feasible to combine radar and citizen science data with individual tracks, acoustic monitoring, landscape genomics, and technologies that have yet to be developed. It is an exciting time to study avian migration across scales. 


<!--   + Application: bird forecasts for conservation, in concert with understanding effects of light pollution. "Lights off inititatives." Forecasts can also engage the public with nature and indirectly lead to better conservation outcomes through increased awareneses.  -->
<!--   + Outlooks in an era of big data ecology  -->
<!--     + more applications of machine learning -->
<!--     + Bring together complementary "big" datasets, like radar and citizen science initiatives. -->
<!--       + Have demonstrated that this can lead to new insights (Appendix - Gulf of Mexico work) -->
<!--       + Discuss in more detail future modeling plans  -->
<!--   + New technology for tracking birds: acoustic monitoring on the ground, microphones on birds, light sensors -->
<!--   + Future studies should incorporate work across scales to gain varied and *complementary* perspectives on natural phenomena -->
<!--     + The interplay of individual traits, evolutionary pressures, external cues and threats, changing habitats. Able to understand drivers of behavior on multiple levels -->
<!-- + potential hypothesis of climate change causing more variation, in addition to shifts (a la flycatcher patterns, with small sample sizes) -->

\printbibliography[segment=\therefsection,heading=subbibliography]