---
output:
  pdf_document: default
  html_document: default
---


Migratory birds form a network of organisms that connect the world, serving as indicators of ecosystem health and biodiversity on a hemispheric scale. Unfortunately, avian migrants are threatened by the rapidly increasing pressures of global change. Understanding the capabilities of migratory birds to respond to established and emerging challenges requires knowledge of the complex interactions among individuals, populations, species, and natural and built environments. In this thesis, I surveyed the drivers of bird migration across scales. I focused on the contributions of the innate migratory program, birds' responses to environmental cues and conditions, and the influence of human activity on migratory behavior.

First, I investigated birds' innate migratory programs. I demonstrated that stonechats (genus *Saxicola*) possess inherited programs that vary among taxa according to migratory tendency, but also readily interact with environmental factors to influence migratory phenotypes (chapter \@ref(stonechats)). Next, I combined field and laboratory studies to show that ongoing responses to climate change in a long-distance migrant, the pied flycatcher (*Ficedula hypoleuca*), involve not only phenotypic plasticity, but microevolutionary change as well (chapter \@ref(flycatchers)). I then shifted to a wild context and examined the migration of the Eurasian blackcap (*Sylvia atricapilla*) across its European range, illustrating two different ways that natural selection can act on migratory strategies (chapter \@ref(blackcap-geo)). Expanding to a continental perspective, I showed that migratory flexibility is important not only on evolutionary timescales, but also to enable short-term responses to variable environmental conditions during active migratory flights---and that these responses are predictable enough to reliably forecast avian movements (chapter \@ref(forecast)). Finally, I focused on human impacts on migration, showing that artificial light at night can drastically affect migratory journeys (chapter \@ref(lights)). Human activity impacts not only migrants' in-flight behaviors, but it can also shape their broader ecology (chapter \@ref(blackcap-uk)). Overall, this these work shows that the flexibility we observe in migratory birds stems from a range of sources, innate and external, and that variation in migratory phenotypes may be key to responding to environmental change.
